<?php

namespace VoitureBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * VoitureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoitureRepository extends \Doctrine\ORM\EntityRepository
{
    public function Prix($prix)
    {
      $qb = $this->createQueryBuilder('v');
      $qb->where('v.prix > :prix')
        ->setParameter('prix', $prix);
      return $qb->getQuery()
                ->getResult();
    }

    public function Recherche($libelle)
    {
      $qb = $this->createQueryBuilder('v');
      $qb->where('v.nom LIKE :libelle')
          ->setParameter('libelle', '%'.$libelle.'%');
      return $qb->getQuery()
                ->getResult();
    }

    public function findArray($array)//panier dans le session
    {
        $qb = $this->createQueryBuilder('v')
                    ->select('v')
                    ->Where('v.id IN (:array)')
                    ->setParameter('array', $array);
                    
    return $qb->getQuery()->getResult();
    }
}
