<?php

namespace VetementBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;


/**
 * VetementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VetementRepository extends \Doctrine\ORM\EntityRepository
{
    public function Cherche($libelle)
    {
      $qb = $this->createQueryBuilder('v');
      $qb->where('v.libelle LIKE :libelle')
          ->setParameter('libelle', '%'.$libelle.'%');
      return $qb->getQuery()
                ->getResult();
    }

    public function findArray($array)
    {
        $qb = $this->createQueryBuilder('v')
                    ->select('v')
                    ->Where('v.id IN (:array)')
                    ->setParameter('array', $array);
                    
    return $qb->getQuery()->getResult();
    }

    public function Prix($prix)
    {
      $qb = $this->createQueryBuilder('c');
      $qb->where('c.prix < :prix')
        ->setParameter('prix', $prix);
      return $qb->getQuery()
                ->getResult();
    }
}
