imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: vetement_admin.yml }
    - { resource: voiture_admin.yml }
    - { resource: chauss_admin.yml }
    - { resource: prop_admin.yml }
    - { resource: client_admin.yml }
    - { resource: fournisseur_admin.yml }
    - { resource: "@AcmeUserBundle/Resources/config/services.yml" }
    - { resource: "@VetementBundle/Resources/config/services.yml" }
    - { resource: "@VoitureBundle/Resources/config/services.yml" }
    - { resource: "@ChaussureBundle/Resources/config/services.yml" }
    - { resource: "@CommentaireBundle/Resources/config/services.yml" }
    - { resource: "@FournisseurBundle/Resources/config/services.yml" }
    - { resource: "@ClientBundle/Resources/config/services.yml" }
    - { resource: "@ProprietaireBundle/Resources/config/services.yml" }
    

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr
    app.path.product_images: '../web/uploads/image/products'

framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        pathToWeb: "%kernel.project_dir%/web"

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    encryption: '%mailer_encryption%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: AppBundle\Entity\User
    service:                               
        mailer: fos_user.mailer.twig_swift # this lines
    from_email:
        address: you@example.com
        sender_name: You

vich_uploader:
    db_driver: orm
    mappings:
        product_images:
            uri_prefix:         '%app.path.product_images%'
            upload_destination: '%kernel.root_dir%/../web/uploads/image/products'


knp_snappy:
    pdf:
       enabled:    true
       binary:     '"C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe"'
       options: []
           

    image:
       enabled:    true
       binary:     '"C:\Program Files\wkhtmltopdf\bin\wkhtmltoimage.exe"' 
       options: []


       

